baseurl             = "https://thecoducer.github.io/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "cocoa-hugo-theme"
author              = "Mayukh Datta"
title               = "Mayukh Datta"
pygmentsuseclasses  = true
disqusshortname     = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false
googleAnalytics     = "UA-103801408-1"

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -130
identifier             = "blog"
url                    = "http://www.thecoducer.com/p/archive.html"

[[menu.main]]
name                   = "Photo+Blog"
weight                 = -120
identifier             = "photoblog"
url                    = "https://somethingsomewhere9.wordpress.com/"

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "http://www.thecoducer.com/p/about-mayukhdatta.html"

[params]
latestpostscount       = 5                            # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "Mayukh Datta"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Personal Website of Mayukh Datta."
email                  = "mayukh5741@gmail.com"
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/thecoducer.ico"
github                 = "//github.com/thecoducer"
highlightjs            = true
instagram              = "//instagram.com/thecoducer"
lang                   = "en"
linkedin               = "//linkedin.com/in/mayukhdatta5741"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
selfintro              = "I write codes. Wander & take photos. Love to pursue art. Enthusiastic about AI and cyber security."                            # appears in the site header when set to a non-empty string
twitter                = "//twitter.com/thecoducer"
facebook               = "//facebook.com/thecoducer"
# highlightjslanguages = ["go"]                        # additional languages not included in the "common" set
# highlightjsStyle     = "darcula"

piwik				   = false                         # If true, Piwik integration is enabled
# piwik_url            = "//www.example.com/piwik/"    # URL to your Piwik installation. Must End with a slash
# piwik_id			   = 2                             # Id of your site in Piwik

avatar                 = "img/profile.png" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# gravatar             = ""                # do not use in the same time as avatar

# The following are DEPRECATED.
gatracker              = "XYZ" # use googleAnalytics instead
initials               = "ad"  # displayed on single post page; deprecated in v0.3.0.
